const earbud = [
  {
    id: 1,
    title:
      "boAt Airdopes 141 Bluetooth Truly Wireless in Ear Earbuds with 42H Playtime, Beast Mode(Low Latency Upto 80ms) for Gaming, IPX4 Water Resistance, ENx Tech, IWP, Smooth Touch Controls(Cyan Cider)",
    img: "https://m.media-amazon.com/images/I/31BMd11KciL._SY300_SX300_.jpg",
    img2: "https://m.media-amazon.com/images/I/51IIMMnQ7cL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/81NXl8ObnEL._SY450_.jpg",
    img4: "https://m.media-amazon.com/images/I/71Dbhs4BLZL._SY450_.jpg",
    img5: "https://m.media-amazon.com/images/I/71DxKhGrLuL._SY450_.jpg",
    price: 4490,
    discount: 78,
    qty: 1,
    category: "earbud",
  },
  {
    id: 2,
    title:
      "CrossBeats Newly launched Revolt Hybrid Active Noise Cancelling Wireless Bluetooth Earbuds, 48hrs Playtime TWS, 10 mm Ti-Alloy Driver, EchoBlast™, 40ms Low Latency Earphone-Black",
    img: "https://m.media-amazon.com/images/I/61J9BzebDnL._SY450_.jpg",
    img2: "https://m.media-amazon.com/images/I/61f1IQifWXL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/61axYGTUdVL._SY450_.jpg",
    img4: "https://m.media-amazon.com/images/I/81o04TvhnIL._SY450_.jpg",
    img5: "https://m.media-amazon.com/images/I/61t9SMyZ9aL._SY450_.jpg",
    price: 9999,
    discount: 75,
    qty: 1,
    category: "earbud",
  },
  {
    id: 3,
    title:
      "OnePlus Nord Buds True Wireless in Ear Earbuds with Mic, 12.4mm Titanium Drivers, Playback:Up to 30hr case, 4-Mic Design + AI Noise Cancellation, IP55 Rating, Fast Charging (Black Slate)",
    img: "https://m.media-amazon.com/images/I/51ws0E8cnbL._SL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/51ws0E8cnbL._SL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/51gX3E0vzjL._SL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/41-vUVwh5VL._SL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/51PDeyFzo1L._SL1500_.jpg",
    price: 2999,
    discount: 7,
    qty: 1,
    category: "earbud",
  },
  {
    id: 4,
    title:
      "pTron Bassbuds Duo in Ear Earbuds with 32Hrs Total Playtime, Bluetooth 5.1 Wireless, Stereo Audio, Touch Control TWS, with Mic, Type-C Fast Charging, IPX4 & Voice Assistance (Black)",
    img: "https://m.media-amazon.com/images/I/31G1NouVxaL._SY300_SX300_.jpg",
    img2: "https://m.media-amazon.com/images/I/61Coiv6SLXL._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/61jkqxMB4jL._SY450_.jpg",
    img4: "https://m.media-amazon.com/images/I/51+tZ3xiA7L._SL1100_.jpg",
    img5: "https://m.media-amazon.com/images/I/51wi0sZVqyL._SL1100_.jpg",
    price: 2599,
    discount: 71,
    qty: 1,
    category: "earbud",
  },
  {
    id: 5,
    title:
      "Boult Audio Z25 True Wireless in Ear Earbuds with 32H Playtime, 45ms Low Latency, Type-C Fast Charging (10=150Mins), Made in India, Zen ENC Mic, 13mm Bass Drivers, Bluetooth 5.3 Ear Buds (Blue Moss)",
    img: "https://m.media-amazon.com/images/I/71vlByXS-JL._SL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/81KqErUpBOL._SL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/81v+dv-6KAL._SL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/71akRKumeCL._SL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/81T79XX+wUL._SL1500_.jpg",
    price: 2999,
    discount: 63,
    qty: 1,
    category: "earbud",
  },
  {
    id: 6,
    title:
      "Boult Audio X30 True Wireless in Ear Earbuds with 40H Playtime, Quad Mic ENC, 45ms Xtreme Low Latency, Made in India, Type-C Fast Charging, 3 Equalizer Modes (Rock, BoomX, Hi-Fi), BT 5.1 (Blue)",
    img: "https://m.media-amazon.com/images/I/71ey9w1JYTL._SL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/71xO47tyYsL._SL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/71m50Eny0EL._SL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/61RgoMA9XDL._SL1500_.jpg",
    img5: "	https://m.media-amazon.com/images/I/81OBQ+eI1uL._SL1500_.jpg",
    price: 4999,
    discount: 70,
    qty: 1,
    category: "earbud",
  },
  {
    id: 7,
    title:
      "boAt Airdopes 121v2 in-Ear True Wireless Earbuds with Upto 14 Hours Playback, 8MM Drivers, Battery Indicators, Lightweight Earbuds & Multifunction Controls (Active Black, with Mic)",
    img: "https://m.media-amazon.com/images/I/61o2urRxrcL._SL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/61o2urRxrcL._SL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/61j3VLyxkHL._SL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/61aBVyNtImL._SL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/71JFUxjducL._SL1500_.jpg",
    price: 2990,
    discount: 57,
    qty: 1,
    category: "earbud",
  },
  {
    id: 8,
    title:
      "Blaupunkt BTW07 ANC Moksha-30Db Bluetooth Truly Wireless In Ear Earbuds with Mic, Flip Top Rotatory Design, 40H Playtime, TurboVolt Fast Charging, Crispr Enc Tech, GameOn with 80Ms Low Latency (Black)",
    img: "https://m.media-amazon.com/images/I/31XeLoY52sL._SY300_SX300_.jpg",
    img2: "https://m.media-amazon.com/images/I/61iJdWkaQ+L._SY450_.jpg",
    img3: "https://m.media-amazon.com/images/I/71Tg5d5phGL._SY450_.jpg",
    img4: "https://m.media-amazon.com/images/I/61KdB+bNUFL._SY450_.jpg",
    img5: "https://m.media-amazon.com/images/I/61lxhBySpLL._SY450_.jpg",
    price: 5999,
    discount: 58,
    qty: 1,
    category: "earbud",
  },
  {
    id: 10,
    title: `pTron Bassbuds Fute 5.1 Bluetooth Truly Wireless Featherlite TWS in Ear Earbuds with Mic 25Hrs Playtime, 13Mm Dynamic Driver, Immersive Audio, Touch Control, Voice Assistance & Fast Charging (Black)`,
    img: "https://m.media-amazon.com/images/I/51PNGyUNvmL._SL1100_.jpg",
    img2: "https://m.media-amazon.com/images/I/61dElFbRplL._SL1100_.jpg",
    img3: "https://m.media-amazon.com/images/I/51Im+twUG4L._SL1100_.jpg",
    img4: "https://m.media-amazon.com/images/I/61un6wGaIjL._SL1100_.jpg",
    img5: "https://m.media-amazon.com/images/I/513-c5luOmL._SL1100_.jpg",
    price: 3299,
    discount: 79,
    qty: 1,
    category: "earbud",
  },
  {
    id: 11,
    title: `Boult Audio X1 Buds True Wireless in Ear Earbuds with 24H Playtime, Quad Mic ENC, Made in India, Type-C Fast Charging, Environmental Noise Cancellation, 10mm Bass Drivers, TWS Airbass ear buds (Black)`,
    img: "https://m.media-amazon.com/images/I/71mT2gCHH+L._SL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/81Nov7kscML._SL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/91teZ0CgAKL._SL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/71aL6iUS8KL._SL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/71o4W7JuPtL._SL1500_.jpg",
    price: 6999,
    discount: 74,
    qty: 1,
    category: "earbud",
  },
  {
    id: 12,
    title: `Boult Audio Powerbuds True Wireless in Ear Earbuds with 120H Playtime, in-Built Powerbank, Type-C Fast Charging, Made in India, Pro+ Calling HD Mic, IPX7 Waterproof, Bluetooth Ear Buds TWS (Black)`,
    img: "https://m.media-amazon.com/images/I/71jrExswt4L._SL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/71HAe9bru5L._SL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/71wUXtQVVjL._SL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/81r6fKyraKL._SL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/71-cfdI-CBL._SL1500_.jpg",
    price: 8999,
    discount: 83,
    qty: 1,
    category: "earbud",
  },
  {
    id: 13,
    title: `Noise Buds Vs104 Bluetooth Truly Wireless in Ear Earbuds with Mic, 30-Hours of Playtime, Instacharge, 13Mm Driver and Hyper Sync (Charcoal Black)`,
    img: "https://m.media-amazon.com/images/I/51cjIEYU8BL._SL1500_.jpg",
    img2: "https://m.media-amazon.com/images/I/61gE89QmD+L._SL1500_.jpg",
    img3: "https://m.media-amazon.com/images/I/51r57IhfBwL._SL1500_.jpg",
    img4: "https://m.media-amazon.com/images/I/513az8Cho7L._SL1500_.jpg",
    img5: "https://m.media-amazon.com/images/I/517pNu7bWJL._SL1500_.jpg",
    price: 3499,
    discount: 69,
    qty: 1,
    category: "earbud",
  },
];

const Smart_Watch = [
  {
    id: 101,
    title: `beatXP Marv Neo 1.85” (4.6 cm) Display, Bluetooth Calling Smart Watch, Smart AI Voice Assistant, 100+ Sports Modes, Heart & SpO2 Monitoring, IP68, Fast Charging (Free Size, Modern, Black)`,
    img: "https://m.media-amazon.com/images/I/61TXR+7EpUL._SX679_.jpg",
    img2: "https://m.media-amazon.com/images/I/71P5XNXbOcL._SX679_.jpg",
    img3: "https://m.media-amazon.com/images/I/71DTPUfYSzL._SX679_.jpg",
    price: 6499,
    discount: 82,
    qty: 1,
    category: "Smart Watch"
  },
  {
    id: 102,
    title: ``,
    img: "",
    img2: "",
    img3: "",
    price: 0,
    discount: 0,
    qty: 1,
    category: "Smart Watch"
  },
  {
    id: 103,
    title: ``,
    img: "",
    img2: "",
    img3: "",
    price: 0,
    discount: 0,
    qty: 1,
    category: "Smart Watch"
  },
  {
    id: 104,
    title: ``,
    img: "",
    img2: "",
    img3: "",
    price: 0,
    discount: 0,
    qty: 1,
    category: "Smart Watch"
  }
]