const products = [
  {
    id: 1,
    title:
      "boAt Airdopes 141 Bluetooth Truly Wireless in Ear Earbuds with 42H Playtime, Beast Mode(Low Latency Upto 80ms) for Gaming, IPX4 Water Resistance, ENx Tech, IWP, Smooth Touch Controls(Cyan Cider)",
    img: "https://m.media-amazon.com/images/I/31BMd11KciL._SY300_SX300_.jpg",
    price: 4490,
    discount: 78,
    qty: 1,
    category: "earbud",
  },
  {
    id: 2,
    title:
      "CrossBeats Newly launched Revolt Hybrid Active Noise Cancelling Wireless Bluetooth Earbuds, 48hrs Playtime TWS, 10 mm Ti-Alloy Driver, EchoBlast™, 40ms Low Latency Earphone-Black",
    img: "https://m.media-amazon.com/images/I/61J9BzebDnL._SY450_.jpg",
    price: 9999,
    discount: 75,
    qty: 1,
    category: "earbud",
  },
  {
    id: 3,
    title:
      "OnePlus Nord Buds True Wireless in Ear Earbuds with Mic, 12.4mm Titanium Drivers, Playback:Up to 30hr case, 4-Mic Design + AI Noise Cancellation, IP55 Rating, Fast Charging (Black Slate)",
    img: "https://m.media-amazon.com/images/I/51ws0E8cnbL._SL1500_.jpg",
    price: 2999,
    discount: 7,
    qty: 1,
    category: "earbud",
  },
  {
    id: 4,
    title:
      "pTron Bassbuds Duo in Ear Earbuds with 32Hrs Total Playtime, Bluetooth 5.1 Wireless, Stereo Audio, Touch Control TWS, with Mic, Type-C Fast Charging, IPX4 & Voice Assistance (Black)",
    img: "https://m.media-amazon.com/images/I/31G1NouVxaL._SY300_SX300_.jpg",
    price: 2599,
    discount: 71,
    qty: 1,
    category: "earbud",
  },
  {
    id: 5,
    title:
      "Boult Audio Z25 True Wireless in Ear Earbuds with 32H Playtime, 45ms Low Latency, Type-C Fast Charging (10=150Mins), Made in India, Zen ENC Mic, 13mm Bass Drivers, Bluetooth 5.3 Ear Buds (Blue Moss)",
    img: "https://m.media-amazon.com/images/I/71vlByXS-JL._SL1500_.jpg",
    price: 2999,
    discount: 63,
    qty: 1,
    category: "earbud",
  },
  {
    id: 6,
    title:
      "Boult Audio X30 True Wireless in Ear Earbuds with 40H Playtime, Quad Mic ENC, 45ms Xtreme Low Latency, Made in India, Type-C Fast Charging, 3 Equalizer Modes (Rock, BoomX, Hi-Fi), BT 5.1 (Blue)",
    img: "https://m.media-amazon.com/images/I/71ey9w1JYTL._SL1500_.jpg",
    price: 4999,
    discount: 70,
    qty: 1,
    category: "earbud",
  },
  {
    id: 7,
    title:
      "boAt Airdopes 121v2 in-Ear True Wireless Earbuds with Upto 14 Hours Playback, 8MM Drivers, Battery Indicators, Lightweight Earbuds & Multifunction Controls (Active Black, with Mic)",
    img: "https://m.media-amazon.com/images/I/61o2urRxrcL._SL1500_.jpg",
    price: 2990,
    discount: 57,
    qty: 1,
    category: "earbud",
  },
  {
    id: 8,
    title:
      "Blaupunkt BTW07 ANC Moksha-30Db Bluetooth Truly Wireless In Ear Earbuds with Mic, Flip Top Rotatory Design, 40H Playtime, TurboVolt Fast Charging, Crispr Enc Tech, GameOn with 80Ms Low Latency (Black)",
    img: "https://m.media-amazon.com/images/I/31XeLoY52sL._SY300_SX300_.jpg",
    price: 5999,
    discount: 58,
    qty: 1,
    category: "earbud",
  },
  {
    id: 10,
    title: `pTron Bassbuds Fute 5.1 Bluetooth Truly Wireless Featherlite TWS in Ear Earbuds with Mic 25Hrs Playtime, 13Mm Dynamic Driver, Immersive Audio, Touch Control, Voice Assistance & Fast Charging (Black)`,
    img: "https://m.media-amazon.com/images/I/51PNGyUNvmL._SL1100_.jpg",
    price: 3299,
    discount: 79,
    qty: 1,
    category: "earbud",
  },
  {
    id: 11,
    title: `Boult Audio X1 Buds True Wireless in Ear Earbuds with 24H Playtime, Quad Mic ENC, Made in India, Type-C Fast Charging, Environmental Noise Cancellation, 10mm Bass Drivers, TWS Airbass ear buds (Black)`,
    img: "https://m.media-amazon.com/images/I/71mT2gCHH+L._SL1500_.jpg",
    price: 6999,
    discount: 74,
    qty: 1,
    category: "earbud",
  },
  {
    id: 12,
    title: `Boult Audio Powerbuds True Wireless in Ear Earbuds with 120H Playtime, in-Built Powerbank, Type-C Fast Charging, Made in India, Pro+ Calling HD Mic, IPX7 Waterproof, Bluetooth Ear Buds TWS (Black)`,
    img: "https://m.media-amazon.com/images/I/71jrExswt4L._SL1500_.jpg",
    price: 8999,
    discount: 83,
    qty: 1,
    category: "earbud",
  },
  {
    id: 13,
    title: `Noise Buds Vs104 Bluetooth Truly Wireless in Ear Earbuds with Mic, 30-Hours of Playtime, Instacharge, 13Mm Driver and Hyper Sync (Charcoal Black)`,
    img: "https://m.media-amazon.com/images/I/51cjIEYU8BL._SL1500_.jpg",
    price: 3499,
    discount: 69,
    qty: 1,
    category: "earbud",
  },
  {
    id: "101",
    title: "Boult Audio Z40 True Wireless in Ear Earbuds with 60H Playtime, Zen™ ENC Mic, Low Latency Gaming, Type-C Fast Charging, Made in India, 10mm Rich Bass Drivers, IPX5, Bluetooth 5.3 Ear Buds TWS (Blue)",
    img: "https://m.media-amazon.com/images/I/71ITkeoYiTL.SL1500.jpg",
    price: 4999,
    discount: 80,
    qty: 1,
    category: "earbud",
  },
  {
    id: "102",
    title: "Noise Buds VS104 Max Truly Wireless in-Ear Earbuds with ANC(Up to 25dB),Up to 45H Playtime, Quad Mic with ENC, Instacharge(10 min=180 min), 13mm Driver, BT v5.3 (Silver Grey)",
    img: "https://m.media-amazon.com/images/I/51AbB+I1pvL.SX522.jpg",
    price: 4999,
    discount: 64,
    qty: 1,
    category: "earbud",
  },
  {
    id: "104",
    title: "Symphony Ice Cube 27 Personal Air Cooler For Home with Powerful Fan, 3-Side Honeycomb Pads, i-Pure Technology and Low Power Consumption (27L, White)",
    img: "https://m.media-amazon.com/images/I/414dASFjmEL.SX522.jpg",
    price: 7999,
    discount: 29,
    qty: 1,
    category: "fan",
  },
  {
    id: "105",
    title: "atomberg Renesa 1200mm BLDC Motor 5 Star Rated Sleek Ceiling Fans with Remote | Upto 65% Energy Saving | 2+1 Year Warranty (Midnight Black) | Winner of National Energy Conservation Awards (2022)",
    img: "https://m.media-amazon.com/images/I/61mhVkkWM-L.SX522.jpg",
    price: 5190,
    discount: 29,
    qty: 1,
    category: "fan",
  },
  {
    id: "106",
    title: "Atomberg Renesa 400mm Pedestal Swing Fan | Silent BLDC Fan with LED Display and 6 Speed | Remote Control with Timer & Sleep Control | 1+1 Year Warranty (Snow White)",
    img: "https://m.media-amazon.com/images/I/61qkh62kfiL.SX522.jpg",
    price: 6140,
    discount: 33,
    qty: 1,
    category: "fan",
  },
  {
    id: "107",
    title: "Philips HL7756/01 Mixer Grinder 750 Watt, 3 Stainless Steel Multipurpose Jars with 3 Speed Control and Pulse function (Black)",
    img: "https://m.media-amazon.com/images/I/71mL2bdyRdL.SX522.jpg",
    price: 5295,
    discount: 30,
    qty: 1,
    category: "mixer",
  },
  {
    id: "108",
    title: "PHILIPS Mixer Grinder 3-in-1 750 Watt (Mixer Grinder + Juicer + Food Processor) 4 Jar, (HL7707/01)",
    img: "https://m.media-amazon.com/images/I/51mCAmdG4AL.SX522.jpg",
    price: 9995,
    discount: 23,
    qty: 1,
    category: "mixer",
  },
  {
    id: "109",
    title: "AGARO Imperial Slow Juicer, Professional Cold Press Whole Slow Juicer, 240 Watts Power Motor, 3 Strainers, All-in-1 Fruit & Vegetable Juicer, Grey/Black",
    img: "https://m.media-amazon.com/images/I/712fOpI7NvL.SX522.jpg",
    price: 35899,
    discount: 62,
    qty: 1,
    category: "mixer",
  },
  {
    id: "110",
    title: "Havells Nutri Art Slow Juicer 200W | Larger Feeding Tube | Ceramic Auger |Lowest Speed 70 RPM |Pulp Controller | Reverse Button | Quick and Easy Cleaning |Lowest Noise | 2Yr Warranty, 200 Watt",
    img: "https://m.media-amazon.com/images/I/61OK2cFsOLL.SX522.jpg",
    price: 26995,
    discount: 35,
    qty: 1,
    category: "mixer",
  }
];
