const Songs = [
    {
        id: 1,
        name: "Dhoom Dhoom Tata Young",
        path: "../src/audio/Dhoom_Dhoom_Tata_Young.mp3",
        singers: "Sunidhi Chauhan - Shaan - Shreya Ghoshal - Abhijeet - Sowmya Raoh - Kunal Ganjawala - Vasundhara Das - KK - Gayatri Ganjawala - Indee (Rap) - Abhishek Bachchan - Tata Young",
        album:"Dhoom",
        audioImg: "../src/audio/thumbs/01dhoom.jpg",
        starCast:"Abhishek Bachchan - Uday Chopra - John Abraham - Esha Deol - Rimi Sen",
        year:2004,
        category:'Party',
        language:'Hindi',
        composedBy:"Pritam"
    },
    {
        id: 2,
        name: "Dhoom Machale",
        path: "../src/audio/Dhoom_Machale.mp3",
        singers: "Sunidhi Chauhan - Shaan - Shreya Ghoshal - Abhijeet - Sowmya Raoh - Kunal Ganjawala - Vasundhara Das - KK - Gayatri Ganjawala - Indee (Rap) - Abhishek Bachchan - Tata Young",
        album:"Dhoom",
        audioImg: "../src/audio/thumbs/01dhoom.jpg",
        starCast:"Abhishek Bachchan - Uday Chopra - John Abraham - Esha Deol - Rimi Sen",
        year:2004,
        category:'Party',
        language:'Hindi',
        composedBy:"Pritam"
    },
    {
        id: 3,
        name: "Salaame",
        path: "../src/audio/Salaame_Dhoom.mp3",
        singers: "Sunidhi Chauhan - Shaan - Shreya Ghoshal - Abhijeet - Sowmya Raoh - Kunal Ganjawala - Vasundhara Das - KK - Gayatri Ganjawala - Indee (Rap) - Abhishek Bachchan - Tata Young",
        album:"Dhoom",
        audioImg: "../src/audio/thumbs/01dhoom.jpg",
        starCast:"Abhishek Bachchan - Uday Chopra - John Abraham - Esha Deol - Rimi Sen",
        year:2004,
        category:'Party',
        language:'Hindi',
        composedBy:"Pritam"
    },
    {
        id: 4,
        name: "Assalaam Vaalekum",
        path: "../src/audio/Assalaam_Vaalekum.mp3",
        singers: "Himesh Reshammiya - Shreya Ghoshal - Sunidhi Chauhan - Asha Bhosle",
        album:"Aap Kaa Surroor",
        audioImg: "../src/audio/thumbs/01aap-kaa-surroor.jpg",
        starCast:"Himesh Reshammiya - Hansika Motwani - Mallika Sherawat",
        year:2007,
        category:'Party',
        composedBy:"Himesh Reshammiya"
    },
    {
        id: 5,
        name: "Tanhaiyaan",
        path: "../src/audio/Tanhaiyaan.mp3",
        singers: "Himesh Reshammiya - Shreya Ghoshal - Sunidhi Chauhan - Asha Bhosle",
        album:"Aap Kaa Surroor",
        audioImg: "../src/audio/thumbs/01aap-kaa-surroor.jpg",
        starCast:"Himesh Reshammiya - Hansika Motwani - Mallika Sherawat",
        year:2007,
        category:'Sad',
        composedBy:"Himesh Reshammiya"
    },
    {
        id: 6,
        name: "Tera Mera Milna",
        path: "../src/audio/Tera_Mera_Milna.mp3",
        singers: "Himesh Reshammiya - Shreya Ghoshal - Sunidhi Chauhan - Asha Bhosle",
        album:"Aap Kaa Surroor",
        audioImg: "../src/audio/thumbs/01aap-kaa-surroor.jpg",
        starCast:"Himesh Reshammiya - Hansika Motwani - Mallika Sherawat",
        year:2007,
        category:'Romantic',
        composedBy:"Himesh Reshammiya"
    },
    {
        id: 7,
        name: "Tere Bina",
        path: "../src/audio/Tere_Bina.mp3",
        singers: "Himesh Reshammiya - Shreya Ghoshal - Sunidhi Chauhan - Asha Bhosle",
        album:"Aap Kaa Surroor",
        audioImg: "../src/audio/thumbs/01aap-kaa-surroor.jpg",
        starCast:"Himesh Reshammiya - Hansika Motwani - Mallika Sherawat",
        year:2007,
        category:'Sad',
        composedBy:"Himesh Reshammiya"
    },
    {
        id: 8,
        name: "Ya Ali",
        path: "../src/audio/Ya_Ali.mp3",
        singers: "Himesh Reshammiya - Shreya Ghoshal - Sunidhi Chauhan - Asha Bhosle",
        album:"Aap Kaa Surroor",
        audioImg: "../src/audio/thumbs/01aap-kaa-surroor.jpg",
        starCast:"Himesh Reshammiya - Hansika Motwani - Mallika Sherawat",
        year:2007,
        category:'Party',
        language:'Hindi',
        composedBy:"Himesh Reshammiya"
    },
    {
        id: 9,
        name: "Aap ki Kashish",
        path: "../src/audio/Aap_Ki_Kashish.mp3",
        singers: "Himesh Reshammiya - Sunidhi Chauhan - Abhijeet Sawant - KK",
        album:"Aashiq Banaya Aapne",
        audioImg: "../src/audio/thumbs/01aashiq-banaya.jpg",
        starCast:"Emraan Hashmi - Sonu Sood - Tanushree Dutta",
        year:2005,
        category:'Love',
        language:'Hindi',
        composedBy:"Himesh Reshammiya"
    },
    {
        id: 10,
        name: "Aashiq Banaya Aapne Title Track",
        path: "../src/audio/Aashiq_Banaya_Aapne.mp3",
        singers: "Himesh Reshammiya - Sunidhi Chauhan - Abhijeet Sawant - KK",
        album:"Aashiq Banaya Aapne",
        audioImg: "../src/audio/thumbs/01aashiq-banaya.jpg",
        starCast:"Emraan Hashmi - Sonu Sood - Tanushree Dutta",
        year:2005,
        category:'Love',
        composedBy:"Himesh Reshammiya"
    },
    {
        id: 11,
        name: "Mar Jaawan Mit Jaawan",
        path: "../src/audio/Mar_Jaawan_Mit_Jaawan.mp3",
        singers: "Himesh Reshammiya - Sunidhi Chauhan - Abhijeet Sawant - KK",
        album:"Aashiq Banaya Aapne",
        audioImg: "../src/audio/thumbs/01aashiq-banaya.jpg",
        starCast:"Emraan Hashmi - Sonu Sood - Tanushree Dutta",
        year:2005,
        category:'Love',
        composedBy:"Himesh Reshammiya"
    },
    {
        id: 12,
        name: "Abrar's Entry Jamal Kudu",
        path: "../src/audio/Abrars_Entry_Jamal_Kudu.mp3",
        singers: "Raghav Chaitanya - Arijit Singh - Shreyas Puranik - Sonu Nigam - Bhupinder Babbal - Vishal Mishra - Manan Bhardwaj - Shreya Ghoshal - B Praak - Ashim Kemson - Harshavardhan Rameshwar",
        album:"Animal",
        audioImg: "../src/audio/thumbs/01animal.jpg",
        starCast:"Ranbir Kapoor - Rashmika Mandanna Anil Kapoor Bobby Deol Tripti Dimri",
        year:2023,
        category:'New Releases',
        composedBy:"Pritam, Jam 8 Shreyas Puranik Harshavardhan Rameshwar Manan Bhardwaj Vishal Mishra Jaani Ashim Kemson Choir"
    },
    {
        id: 13,
        name: "Animal Mass Theme",
        path: "../src/audio/Animal_Mass_Theme.mp3",
        singers: "Raghav Chaitanya - Arijit Singh - Shreyas Puranik - Sonu Nigam - Bhupinder Babbal - Vishal Mishra - Manan Bhardwaj - Shreya Ghoshal - B Praak - Ashim Kemson - Harshavardhan Rameshwar",
        album:"Animal",
        audioImg: "../src/audio/thumbs/01animal.jpg",
        starCast:"Ranbir Kapoor - Rashmika Mandanna Anil Kapoor Bobby Deol Tripti Dimri",
        year:2023,
        category:'New Releases',
        language:'Hindi',
        composedBy:"Pritam, Jam 8 Shreyas Puranik Harshavardhan Rameshwar Manan Bhardwaj Vishal Mishra Jaani Ashim Kemson Choir"
    },
    {
        id: 14,
        name: "Arjan Vailly",
        path: "../src/audio/Arjan_Vailly.mp3",
        singers: "Raghav Chaitanya - Arijit Singh - Shreyas Puranik - Sonu Nigam - Bhupinder Babbal - Vishal Mishra - Manan Bhardwaj - Shreya Ghoshal - B Praak - Ashim Kemson - Harshavardhan Rameshwar",
        album:"Animal",
        audioImg: "../src/audio/thumbs/01animal.jpg",
        starCast:"Ranbir Kapoor - Rashmika Mandanna Anil Kapoor Bobby Deol Tripti Dimri",
        year:2023,
        category:'New Releases',
        composedBy:"Pritam, Jam 8 Shreyas Puranik Harshavardhan Rameshwar Manan Bhardwaj Vishal Mishra Jaani Ashim Kemson Choir"
    },
    {
        id: 15,
        name: "Hua Main",
        path: "../src/audio/Hua_Main.mp3",
        singers: "Raghav Chaitanya - Arijit Singh - Shreyas Puranik - Sonu Nigam - Bhupinder Babbal - Vishal Mishra - Manan Bhardwaj - Shreya Ghoshal - B Praak - Ashim Kemson - Harshavardhan Rameshwar",
        album:"Animal",
        audioImg: "../src/audio/thumbs/01animal.jpg",
        starCast:"Ranbir Kapoor - Rashmika Mandanna Anil Kapoor Bobby Deol Tripti Dimri",
        year:2023,
        category:'New Releases',
        composedBy:"Pritam, Jam 8 Shreyas Puranik Harshavardhan Rameshwar Manan Bhardwaj Vishal Mishra Jaani Ashim Kemson Choir"
    },
    {
        id: 16,
        name: "Saari Duniya Jalaa Denge",
        path: "../src/audio/Saari_Duniya_Jalaa_Denge.mp3",
        singers: "Raghav Chaitanya - Arijit Singh - Shreyas Puranik - Sonu Nigam - Bhupinder Babbal - Vishal Mishra - Manan Bhardwaj - Shreya Ghoshal - B Praak - Ashim Kemson - Harshavardhan Rameshwar",
        album:"Animal",
        audioImg: "../src/audio/thumbs/01animal.jpg",
        starCast:"Ranbir Kapoor - Rashmika Mandanna Anil Kapoor Bobby Deol Tripti Dimri",
        year:2023,
        category:'New Releases',
        composedBy:"Pritam, Jam 8 Shreyas Puranik Harshavardhan Rameshwar Manan Bhardwaj Vishal Mishra Jaani Ashim Kemson Choir"
    },
    {
        id: 17,
        name: "Lo Safar",
        path: "../src/audio/Lo_Safar.mp3",
        singers: "Navraj Hans - Palak Muchhal - Shreya Ghoshal - Parry G - Atif Aslam - Jubin Nautiyal - Ankit Tiwari - Shruti Pathak - Pranaay - Jatinder Singh - Siddharth Basrur - Big Dhillon",
        album:"Baaghi 2",
        audioImg: "../src/audio/thumbs/01baaghi2.jpg",
        starCast:"Tiger Shroff - Disha Patani - Randeep Hooda - Manoj Bajpayee - Prateik Babbar Jacqueline Fernandez",
        year:2018,
        category:'Love',
        composedBy:"Sandeep Shirodkar, Panjabi MC Sandeep Shirodkar, Laxmikant - Pyarelal Arko Mithoon Gourov-Roshin Pranaay"
    },
    {
        id: 18,
        name: "O Saathi",
        path: "../src/audio/O_Saathi.mp3",
        singers: "Navraj Hans - Palak Muchhal - Shreya Ghoshal - Parry G - Atif Aslam - Jubin Nautiyal - Ankit Tiwari - Shruti Pathak - Pranaay - Jatinder Singh - Siddharth Basrur - Big Dhillon",
        album:"Baaghi 2",
        audioImg: "../src/audio/thumbs/01baaghi2.jpg",
        starCast:"Tiger Shroff - Disha Patani - Randeep Hooda - Manoj Bajpayee - Prateik Babbar Jacqueline Fernandez",
        year:2018,
        category:'Love',
        composedBy:"Sandeep Shirodkar, Panjabi MC Sandeep Shirodkar, Laxmikant - Pyarelal Arko Mithoon Gourov-Roshin Pranaay"
    },
    {
        id: 19,
        name: "Soniye Dil Nai Lagda",
        path: "../src/audio/Soniye_Dil_Nayi.mp3",
        singers: "Navraj Hans - Palak Muchhal - Shreya Ghoshal - Parry G - Atif Aslam - Jubin Nautiyal - Ankit Tiwari - Shruti Pathak - Pranaay - Jatinder Singh - Siddharth Basrur - Big Dhillon",
        album:"Baaghi 2",
        audioImg: "../src/audio/thumbs/01baaghi2.jpg",
        starCast:"Tiger Shroff - Disha Patani - Randeep Hooda - Manoj Bajpayee - Prateik Babbar Jacqueline Fernandez",
        year:2018,
        category:'Love',
        composedBy:"Sandeep Shirodkar, Panjabi MC Sandeep Shirodkar, Laxmikant - Pyarelal Arko Mithoon Gourov-Roshin Pranaay"
    },
    {
        id: 20,
        name: "Get Ready To Fight Again",
        path: "../src/audio/Get_Ready_To_Fight_Again.mp3",
        singers: "Navraj Hans - Palak Muchhal - Shreya Ghoshal - Parry G - Atif Aslam - Jubin Nautiyal - Ankit Tiwari - Shruti Pathak - Pranaay - Jatinder Singh - Siddharth Basrur - Big Dhillon",
        album:"Baaghi 2",
        audioImg: "../src/audio/thumbs/01baaghi2.jpg",
        starCast:"Tiger Shroff - Disha Patani - Randeep Hooda - Manoj Bajpayee - Prateik Babbar Jacqueline Fernandez",
        year:2018,
        category:'Motivational',
        language:'Hindi',
        composedBy:"Sandeep Shirodkar, Panjabi MC Sandeep Shirodkar, Laxmikant - Pyarelal Arko Mithoon Gourov-Roshin Pranaay"
    },
    {
        id: 21,
        name: "Jay Jaykara",
        path: "../src/audio/Jay_Jaykara.mp3",
        singers: "Daler Mehndi - Sanjeev Chimmalgi - Ramya Behara - Aditi Paul - Deepu - Madhushree - Kailash Kher - Kaala Bhairava",
        album:"Baahubali 2",
        audioImg: "../src/audio/thumbs/01baahubali2.jpg",
        starCast:"Prabhas - Anushka Shetty - Ramya Krishna - Sathyaraj",
        year:2017,
        category:'Motivational',
        language:'Hindi',
        composedBy:"M. M. Keeravani"
    },
    {
        id: 22,
        name: "Jiyo re Bahubali",
        path: "../src/audio/Jiyo_Re_Bahubali.mp3",
        singers: "Daler Mehndi - Sanjeev Chimmalgi - Ramya Behara - Aditi Paul - Deepu - Madhushree - Kailash Kher - Kaala Bhairava",
        album:"Baahubali 2",
        audioImg: "../src/audio/thumbs/01baahubali2.jpg",
        starCast:"Prabhas - Anushka Shetty - Ramya Krishna - Sathyaraj",
        year:2017,
        category:'Motivational',
        language:'Hindi',
        composedBy:"M. M. Keeravani"
    },
    {
        id: 23,
        name: "Veeron ke Veer Aa",
        path: "../src/audio/Veeron_Ke_Veer_Aa.mp3",
        singers: "Daler Mehndi - Sanjeev Chimmalgi - Ramya Behara - Aditi Paul - Deepu - Madhushree - Kailash Kher - Kaala Bhairava",
        album:"Baahubali 2",
        audioImg: "../src/audio/thumbs/01baahubali2.jpg",
        starCast:"Prabhas - Anushka Shetty - Ramya Krishna - Sathyaraj",
        year:2017,
        category:'Motivational',
        language:'Hindi',
        composedBy:"M. M. Keeravani"
    },
    
    {
        id: 24,
        name: "Dhoom Again",
        path: "../src/audio/Dhoom_Again.mp3",
        singers: "Sunidhi Chauhan - Pritam - Sameer - Alisha Chinai - KK - Sonu Nigam - Bipasha Basu - Mahalakshmi Iyer - Suzanne - Jojo Mukherjee - Sukhbir - Soham Chakraborty - Vishal Dadlani - Dominique Cerejo - Asif Ali Baig",
        album:"Dhoom 2",
        audioImg: "../src/audio/thumbs/001dhoom2.jpg",
        starCast:"Hrithik Roshan - Abhishek Bachchan - Aishwarya Rai Bachchan - Bipasha Basu - Uday Chopra",
        year:2006,
        category:'Motivational',
        language:'Hindi',
        composedBy:"Pritam"
    },
    {
        id: 25,
        name: "Dil Laga Na",
        path: "../src/audio/Dil_Laga_Na.mp3",
        singers: "Sunidhi Chauhan - Pritam - Sameer - Alisha Chinai - KK - Sonu Nigam - Bipasha Basu - Mahalakshmi Iyer - Suzanne - Jojo Mukherjee - Sukhbir - Soham Chakraborty - Vishal Dadlani - Dominique Cerejo - Asif Ali Baig",
        album:"Dhoom 2",
        audioImg: "../src/audio/thumbs/001dhoom2.jpg",
        starCast:"Hrithik Roshan - Abhishek Bachchan - Aishwarya Rai Bachchan - Bipasha Basu - Uday Chopra",
        year:2006,
        category:'Love',
        language:'Hindi',
        composedBy:"Pritam"
    },
    {
        id: 26,
        name: "Touch Me",
        path: "../src/audio/Touch_Me.mp3",
        singers: "Sunidhi Chauhan - Pritam - Sameer - Alisha Chinai - KK - Sonu Nigam - Bipasha Basu - Mahalakshmi Iyer - Suzanne - Jojo Mukherjee - Sukhbir - Soham Chakraborty - Vishal Dadlani - Dominique Cerejo - Asif Ali Baig",
        album:"Dhoom 2",
        audioImg: "../src/audio/thumbs/001dhoom2.jpg",
        starCast:"Hrithik Roshan - Abhishek Bachchan - Aishwarya Rai Bachchan - Bipasha Basu - Uday Chopra",
        year:2006,
        category:'Love',
        language:'Hindi',
        composedBy:"Pritam"
    },
    {
        id: 27,
        name: "Apna Time Aayega",
        path: "../src/audio/Apna_Time_Aayega.mp3",
        singers: "Ranveer Singh - Spitfire - D-Cypher - BeatRAW - DIVINE - Naezy - Sez On The Beat - Rishi Rich - Midival Punditz - Karsh Kale - Raghu Dixit - D-Cypher - Dub Sharma - DIVINE - Major C - Jasleen Royal - Dub Sharma - Vibha Saraf - Ankur Tewari - Kaam Bhaari - Kaam Bhaari - Ankur Tewari - Mikey McCleary - Ace - Ishq Bector - Prem and Hardeep - Kaka Bhaniawala - Rapper Desi MA - Arjun - Blitz - Viveick Rajagopalan - MC Altaf - Noxious D - Maharya - 100 RBH - MC Todfod",
        album:"Gully Boy",
        audioImg: "../src/audio/thumbs/01gullyboy.jpg",
        starCast:"Ranveer Singh - Alia Bhatt - Prashant Chaturvedi - Kalki Koechlin",
        year:2006,
        category:'Motivational',
        language:'Hindi',
        composedBy:"Spitfire DIVINE, Naezy, Sez On The Beat Rishi Rich Midival Punditz, Karsh Kale, Raghu Dixit Dub Sharma Chandrashekar Kunder Aka Major C Jasleen Royal Dub Sharma, DIVINE Ankur Tewari, Karsh Kale Ankur Tewari, Kaam Bhaari Ankur Tewari, Mikey McCleary Ace, Ishq Bector Prem, Hardeep Viveick Rajagopalan"
    },
    {
        id: 28,
        name: "Mere Gully Mein",
        path: "../src/audio/Mere_Gully_Mein.mp3",
        singers: "Ranveer Singh - Spitfire - D-Cypher - BeatRAW - DIVINE - Naezy - Sez On The Beat - Rishi Rich - Midival Punditz - Karsh Kale - Raghu Dixit - D-Cypher - Dub Sharma - DIVINE - Major C - Jasleen Royal - Dub Sharma - Vibha Saraf - Ankur Tewari - Kaam Bhaari - Kaam Bhaari - Ankur Tewari - Mikey McCleary - Ace - Ishq Bector - Prem and Hardeep - Kaka Bhaniawala - Rapper Desi MA - Arjun - Blitz - Viveick Rajagopalan - MC Altaf - Noxious D - Maharya - 100 RBH - MC Todfod",
        album:"Gully Boy",
        audioImg: "../src/audio/thumbs/01gullyboy.jpg",
        starCast:"Ranveer Singh - Alia Bhatt - Prashant Chaturvedi - Kalki Koechlin",
        year:2006,
        category:'Motivational',
        language:'Hindi',
        composedBy:"Spitfire DIVINE, Naezy, Sez On The Beat Rishi Rich Midival Punditz, Karsh Kale, Raghu Dixit Dub Sharma Chandrashekar Kunder Aka Major C Jasleen Royal Dub Sharma, DIVINE Ankur Tewari, Karsh Kale Ankur Tewari, Kaam Bhaari Ankur Tewari, Mikey McCleary Ace, Ishq Bector Prem, Hardeep Viveick Rajagopalan"
    },
    {
        id: 29,
        name: "Sher Aaya Sher",
        path: "../src/audio/Sher_Aaya_Sher.mp3",
        singers: "Ranveer Singh - Spitfire - D-Cypher - BeatRAW - DIVINE - Naezy - Sez On The Beat - Rishi Rich - Midival Punditz - Karsh Kale - Raghu Dixit - D-Cypher - Dub Sharma - DIVINE - Major C - Jasleen Royal - Dub Sharma - Vibha Saraf - Ankur Tewari - Kaam Bhaari - Kaam Bhaari - Ankur Tewari - Mikey McCleary - Ace - Ishq Bector - Prem and Hardeep - Kaka Bhaniawala - Rapper Desi MA - Arjun - Blitz - Viveick Rajagopalan - MC Altaf - Noxious D - Maharya - 100 RBH - MC Todfod",
        album:"Gully Boy",
        audioImg: "../src/audio/thumbs/01gullyboy.jpg",
        starCast:"Ranveer Singh - Alia Bhatt - Prashant Chaturvedi - Kalki Koechlin",
        year:2006,
        category:'Motivational',
        language:'Hindi',
        composedBy:"Spitfire DIVINE, Naezy, Sez On The Beat Rishi Rich Midival Punditz, Karsh Kale, Raghu Dixit Dub Sharma Chandrashekar Kunder Aka Major C Jasleen Royal Dub Sharma, DIVINE Ankur Tewari, Karsh Kale Ankur Tewari, Kaam Bhaari Ankur Tewari, Mikey McCleary Ace, Ishq Bector Prem, Hardeep Viveick Rajagopalan"
    },
    {
        id: 30,
        name: "Lagdi Lahore",
        path: "../src/audio/Lahore.mp3",
        singers: "Guru Randhawa",
        album:"Lahore",
        audioImg: "../src/audio/thumbs/01lahoreguru.jpg",
        starCast:"Guru Randhawa",
        year:2015,
        category:'Party',
        language:'Punjabi',
        composedBy:"Preet Hundal"
    },
    {
        id: 31,
        name: "Fashion",
        path: "../src/audio/Fashion.mp3",
        singers: "Guru Randhawa",
        album:"Fashion",
        audioImg: "../src/audio/thumbs/01fashionguru.jpeg",
        starCast:"Guru Randhawa",
        year:2016,
        category:'Party',
        language:'Punjabi',
        composedBy:"Rajat Nagpal"
    },
    {
        id: 32,
        name: "Nain Ta Heere",
        path: "../src/audio/Nain_Ta_Heere.mp3",
        singers: "Guru Randhawa",
        album:"Nain Ta Heere",
        audioImg: "../src/audio/thumbs/01lahoreguru.jpg",
        starCast:"Guru Randhawa",
        year:2016,
        category:'',
        language:'Punjabi',
        composedBy:"Asees Kaur"
    },
    {
        id: 33,
        name: "Suit",
        path: "../src/audio/Suit.mp3",
        singers: "Guru Randhawa",
        album:"Suit 2020",
        audioImg: "../src/audio/thumbs/01suitguru.jpg",
        starCast:"Guru Randhawa",
        year:2020,
        category:'Party',
        language:'Punjabi',
        composedBy:"Intense"
    },
    {
        id: 34,
        name: "Hornn Blow",
        path: "../src/audio/Hornn_Blow.mp3",
        singers: "Harrdy Sandhu",
        album:"Hornn Blow",
        audioImg: "../src/audio/thumbs/01hornblow.jpg",
        starCast:"Harrdy Sandhu",
        year:2020,
        category:'Party',
        language:'Punjabi',
        composedBy:"B Praak"
    },
    {
        id: 35,
        name: "Kalaastar",
        path: "../src/audio/Kalaastar.mp3",
        singers: "Yo Yo Honey Singh",
        album:"Kalaastar",
        audioImg: "../src/audio/thumbs/01kalaastar.jpg",
        starCast:"Yo Yo Honey Singh",
        year:2023,
        category:'Party',
        language:'Punjabi',
        composedBy:"Bass Yogi"
    },
    {
        id: 36,
        name: "Chammo",
        path: "../src/audio/Chammo.mp3",
        singers: "Jyotica Tangri - Sohail Sen - Altamash Faridi - Sohail Sen - Vishal Dadlani - Mika Singh - Farhad Samji - Sukhwinder Singh - Shadab Faridi - Shreya Ghoshal - Danish Sabri",
        album:"Housefull 4",
        audioImg: "../src/audio/thumbs/01housefull4.jpg",
        starCast:"Akshay Kumar - Pooja Hegde - Kriti Senon - Ritesh Deishmukh - Bobby Deol - Kriti Kharbanda - Ranjeet - Rana Daggubati - Chunkey Pandey",
        year:2019,
        category:'PartyParty',
        language:'Hindi',
        composedBy:"Sohail Sen Sohail Sen, B Palm Devi Sri Prasad, Laxmikant - Pyarelal, Farhad Samji, Sandeep Shirodkar Farhad Samji"
    },
    {
        id: 37,
        name: "Ek Chumma",
        path: "../src/audio/Ek_Chumma.mp3",
        singers: "Jyotica Tangri - Sohail Sen - Altamash Faridi - Sohail Sen - Vishal Dadlani - Mika Singh - Farhad Samji - Sukhwinder Singh - Shadab Faridi - Shreya Ghoshal - Danish Sabri",
        album:"Housefull 4",
        audioImg: "../src/audio/thumbs/01housefull4.jpg",
        starCast:"Akshay Kumar - Pooja Hegde - Kriti Senon - Ritesh Deishmukh - Bobby Deol - Kriti Kharbanda - Ranjeet - Rana Daggubati - Chunkey Pandey",
        year:2019,
        category:'Party',
        language:'Hindi',
        composedBy:"Sohail Sen Sohail Sen, B Palm Devi Sri Prasad, Laxmikant - Pyarelal, Farhad Samji, Sandeep Shirodkar Farhad Samji"
    },
    {
        id: 38,
        name: "Shaitan Ka Saala",
        path: "../src/audio/Shaitan_Ka_Saala.mp3",
        singers: "Jyotica Tangri - Sohail Sen - Altamash Faridi - Sohail Sen - Vishal Dadlani - Mika Singh - Farhad Samji - Sukhwinder Singh - Shadab Faridi - Shreya Ghoshal - Danish Sabri",
        album:"Housefull 4",
        audioImg: "../src/audio/thumbs/01housefull4.jpg",
        starCast:"Akshay Kumar - Pooja Hegde - Kriti Senon - Ritesh Deishmukh - Bobby Deol - Kriti Kharbanda - Ranjeet - Rana Daggubati - Chunkey Pandey",
        year:2019,
        category:'Party',
        language:'Hindi',
        composedBy:"Sohail Sen Sohail Sen, B Palm Devi Sri Prasad, Laxmikant - Pyarelal, Farhad Samji, Sandeep Shirodkar Farhad Samji"
    },
    {
        id: 39,
        name: "Besharam Rang",
        path: "../src/audio/Besharam_Rang.mp3",
        singers: "Shilpa Rao - Caralisa Monteiro - Vishal Dadlani - Sheykhar Ravjiani - Arijit Singh - Sukriti Kakar - Shekhar Ravjiani - Sanchit Balhara - Ankit Balhara - Maanya Narang - Riya Duggal - Ankit Balhara - Magdalena Supel - Sanchit Balhara - Kit Bee - Grini - Jamila El Badaoui",
        album:"Pathaan",
        audioImg: "../src/audio/thumbs/01pathaan.jpg",
        starCast:"Shahrukh Khan - Deepika Padukone Shah Rukh Khan - John Abraham",
        year:2023,
        category:'Party',
        language:'Hindi',
        composedBy:"Vishal Sheykhar Vishal Dadlani and Shekhar Ravjiani Sanchit Balhara, Ankit Balhara Ankit Balhara, Sanchit Balhara Vishal and Shekhar"
    },
    {
        id: 40,
        name: "Joome Jo Pathaan",
        path: "../src/audio/Jhoome_Jo_Pathaan.mp3",
        singers: "Shilpa Rao - Caralisa Monteiro - Vishal Dadlani - Sheykhar Ravjiani - Arijit Singh - Sukriti Kakar - Shekhar Ravjiani - Sanchit Balhara - Ankit Balhara - Maanya Narang - Riya Duggal - Ankit Balhara - Magdalena Supel - Sanchit Balhara - Kit Bee - Grini - Jamila El Badaoui",
        album:"Pathaan",
        audioImg: "../src/audio/thumbs/01pathaan.jpg",
        starCast:"Shahrukh Khan - Deepika Padukone Shah Rukh Khan - John Abraham",
        year:2023,
        category:'Party',
        language:'Hindi',
        composedBy:"Vishal Sheykhar Vishal Dadlani and Shekhar Ravjiani Sanchit Balhara, Ankit Balhara Ankit Balhara, Sanchit Balhara Vishal and Shekhar"
    },
    {
        id: 41,
        name: "Qissonmein",
        path: "../src/audio/Qissonmein.mp3",
        singers: "Menuka Poudel - Theertha Subhash - Vedha Laxmi - Srikrishna Vishnubhotla",
        album:"Salaar",
        audioImg: "../src/audio/thumbs/01salaar.jpg",
        starCast:"Prabhas - Shruthi Haasan - Prithviraj",
        year:2023,
        category:'New Releases',
        language:'Hindi',
        composedBy:"Ravi Basrur"
    },
    {
        id: 42,
        name: "Salaar bgm trailer",
        path: "../src/audio/Salaar_bgm_trailer.mp3",
        singers: "Menuka Poudel - Theertha Subhash - Vedha Laxmi - Srikrishna Vishnubhotla",
        album:"Salaar",
        audioImg: "../src/audio/thumbs/01salaar.jpg",
        starCast:"Prabhas - Shruthi Haasan - Prithviraj",
        year:2023,
        category:'New Releases',
        language:'Hindi',
        composedBy:"Ravi Basrur"
    },
    {
        id: 43,
        name: "Salaar bgm",
        path: "../src/audio/Salaar_bgm.mp3",
        singers: "Menuka Poudel - Theertha Subhash - Vedha Laxmi - Srikrishna Vishnubhotla",
        album:"Salaar",
        audioImg: "../src/audio/thumbs/01salaar.jpg",
        starCast:"Prabhas - Shruthi Haasan - Prithviraj",
        year:2023,
        category:'New Releases',
        language:'Hindi',
        composedBy:"Ravi Basrur"
    },
    {
        id: 44,
        name: "Salaar Final Punch",
        path: "../src/audio/Salaar_Final_Punch.mp3",
        singers: "Menuka Poudel - Theertha Subhash - Vedha Laxmi - Srikrishna Vishnubhotla",
        album:"Salaar",
        audioImg: "../src/audio/thumbs/01salaar.jpg",
        starCast:"Prabhas - Shruthi Haasan - Prithviraj",
        year:2023,
        category:'New Releases',
        language:'Hindi',
        composedBy:"Ravi Basrur"
    },
    {
        id: 45,
        name: "Too Much Dimitri Vegas",
        path: "../src/audio/Too_Much_Dimitri_Vegas.mp3",
        singers: "Dimitri Vegas, Like Mike, Dvbbs, Roy Woods",
        album:"Too Much 2021",
        audioImg: "../src/audio/thumbs/01toomuch.jpg",
        starCast:"N/A",
        year:2021,
        category:'Motivational',
        language:'English',
        composedBy:"Michael Thivaios, Denzel Spencer, Christopher Van Den Hoef, Alexander Van Den Hoef, Christian Dold"
    },
    {
        id: 46,
        name: "Your Power Billie Eilish",
        path: "../src/audio/Your_Power_Billie_Eilish.mp3",
        singers: "Billie Eilish",
        album:"Your Power",
        audioImg: "../src/audio/thumbs/01yourpower.jpg",
        starCast:"N/A",
        year:2021,
        category:'Motivational',
        language:'English',
        composedBy:"Billie Eilish"
    },
    {
        id: 47,
        name: "Sorry",
        path: "../src/audio/Sorry_Alan_Walker.mp3",
        singers: "Alan Walker - Isak",
        album:"Sorry",
        audioImg: "../src/audio/thumbs/01sorry.jpg",
        starCast:"N/A",
        year:2021,
        category:'Motivational',
        language:'English',
        composedBy:"Alan Walker, James Njie, Sander Meland"
    },
    {
        id: 48,
        name: "Provide",
        path: "../src/audio/Provide_G_Eazy.mp3",
        singers: "G-Eazy",
        album:"Provide",
        audioImg: "../src/audio/thumbs/01provide.jpg",
        starCast:"N/A",
        year:2021,
        category:'Motivational',
        language:'English',
        composedBy:"Chris Brown, Mark Morrison, Gerald Gillum, Christian Ward, Carl Mccormick, Gabrielle Nowee, Drew Lov"
    },
    {
        id: 49,
        name: "Paro",
        path: "../src/audio/Paro_Nej.mp3",
        singers: "Nej",
        album:"Paro-Nej 2021",
        audioImg: "../src/audio/thumbs/01provide.jpg",
        starCast:"N/A",
        year:2021,
        category:'Motivational',
        language:'English',
        composedBy:"Nasraddine Mona"
    },
    {
        id: 50,
        name: "Masterpiece",
        path: "../src/audio/Masterpiece.mp3",
        singers: "DaBaby",
        album:"Masterpiece",
        audioImg: "../src/audio/thumbs/01masterpiece.jpg",
        starCast:"N/A",
        year:2021,
        category:'Motivational',
        language:'English',
        composedBy:"DaBaby"
    },
    {
        id: 51,
        name: "Deva Shree Ganesha",
        path: "../src/audio/Deva_Shree_Ganesha.mp3",
        singers: "Ajay Gogavale, Ajay-Atul",
        album:"Agneepath",
        audioImg: "../src/audio/thumbs/01agneepath.jpg",
        starCast:"Hrithik Roshan, Sanjay Dutt, Priyanka Chopra",
        year:2012,
        category:'Devotional',
        language:'Hindi',
        composedBy:"Ajay Gogavale, Atul Gogavale"
    },
    {
        id: 52,
        name: "Jay Shri Ram",
        path: "../src/audio/Jai_Shri_Ram.mp3",
        singers: "Manoj Muntashir",
        album:"Adipurush",
        audioImg: "../src/audio/thumbs/01adipurush.jpg",
        starCast:"Prabhas - Kriti Sanon - Saif Ali Khan",
        year:2023,
        category:'Devotional',
        language:'Hindi',
        composedBy:"Ajay-Atul Sachet-Parampara"
    },
    {
        id: 53,
        name: "Ram Siya Ram",
        path: "../src/audio/Ram_Siya_Ram.mp3",
        singers: "Sachet-Parampara",
        album:"Adipurush",
        audioImg: "../src/audio/thumbs/01adipurush.jpg",
        starCast:"Prabhas - Kriti Sanon - Saif Ali Khan",
        year:2023,
        category:'Devotional',
        language:'Hindi',
        composedBy:"Ajay-Atul Sachet-Parampara"
    },
    {
        id: 54,
        name: "Shankara re Shankara",
        path: "../src/audio/Shankara_re_Shankara.mp3",
        singers: "Adarsh Shinde, Mehul Vyas",
        album:"Tanhaji - The Unsung Warrior",
        audioImg: "../src/audio/thumbs/01tanhaji.jpg",
        starCast:"Ajay Devgn, Kajol, Sharad Kelkar, Saif Ali Khan",
        year:2020,
        category:'Devotional',
        language:'Hindi',
        composedBy:"Mehul Vyas Ajay-Atul Sachet-Parampara"
    },
    {
        id: 55,
        name: "Jai Jai Shivshankar",
        path: "../src/audio/Jai_Jai_ShivShankar.mp3",
        singers: "Vishal Dadlani, Benny Dayal",
        album:"War",
        audioImg: "../src/audio/thumbs/01war.jpg",
        starCast:"Hrithik Roshan, Tiger Shroff, Vaani Kapoor",
        year:2019,
        category:'Devotional',
        language:'Hindi',
        composedBy:"Vishal-Shekhar Sanchit Balhara, Ankit Balhara"
    },
    {
        id: 56,
        name: "Hanuman Chalisa - HanuMan",
        path: "../src/audio/Hanuman_Chalisa_Hanuman.mp3",
        singers: "Saicharan Bhaskaruni",
        album:"HanuMan",
        audioImg: "../src/audio/thumbs/01hanuman.jpg",
        starCast:"N/A",
        year:2023,
        category:'Devotional',
        language:'Hindi',
        composedBy:"GowraHari"
    },
    {
        id: 57,
        name: "Ram Naam - Sachet Parampara",
        path: "../src/audio/Ram_Naam.mp3",
        singers: "Sachet - Parampara",
        album:"Ram Mandir Ayodhya 2024",
        audioImg: "../src/audio/thumbs/01ramnaam.jpg",
        starCast:"N/A",
        year:2023,
        category:'Devotional',
        language:'Hindi',
        composedBy:"Sachet - Parampara"
    },
    {
        id: 58,
        name: "Namo Namo",
        path: "../src/audio/Namo_Namo.mp3",
        singers: "Amit Trivedi",
        album:"Kedarnath",
        audioImg: "../src/audio/thumbs/01kedarnath.jpg",
        starCast:"Sushant Singh Rajput, Sara Ali Khan",
        year:2019,
        category:'Devotional',
        language:'Hindi',
        composedBy:"Amit Trivedi"
    },
]


export default Songs