const products = [
  {
    id: 1,
    title:
      "boAt Airdopes 141 Bluetooth Truly Wireless in Ear Earbuds with 42H Playtime, Beast Mode(Low Latency Upto 80ms) for Gaming, IPX4 Water Resistance, ENx Tech, IWP, Smooth Touch Controls(Cyan Cider)",
    img: "https://m.media-amazon.com/images/I/31BMd11KciL._SY300_SX300_.jpg",
    price: 4490,
    discount: 78,
    qty: 1,
    category: "earbud",
  },
  {
    id: 2,
    title:
      "CrossBeats Newly launched Revolt Hybrid Active Noise Cancelling Wireless Bluetooth Earbuds, 48hrs Playtime TWS, 10 mm Ti-Alloy Driver, EchoBlast™, 40ms Low Latency Earphone-Black",
    img: "https://m.media-amazon.com/images/I/61J9BzebDnL._SY450_.jpg",
    price: 9999,
    discount: 75,
    qty: 1,
    category: "earbud",
  },
  {
    id: 3,
    title:
      "OnePlus Nord Buds True Wireless in Ear Earbuds with Mic, 12.4mm Titanium Drivers, Playback:Up to 30hr case, 4-Mic Design + AI Noise Cancellation, IP55 Rating, Fast Charging (Black Slate)",
    img: "https://m.media-amazon.com/images/I/51ws0E8cnbL._SL1500_.jpg",
    price: 2999,
    discount: 7,
    qty: 1,
    category: "earbud",
  },
  {
    id: 4,
    title:
      "pTron Bassbuds Duo in Ear Earbuds with 32Hrs Total Playtime, Bluetooth 5.1 Wireless, Stereo Audio, Touch Control TWS, with Mic, Type-C Fast Charging, IPX4 & Voice Assistance (Black)",
    img: "https://m.media-amazon.com/images/I/31G1NouVxaL._SY300_SX300_.jpg",
    price: 2599,
    discount: 71,
    qty: 1,
    category: "earbud",
  },
  {
    id: 5,
    title:
      "Boult Audio Z25 True Wireless in Ear Earbuds with 32H Playtime, 45ms Low Latency, Type-C Fast Charging (10=150Mins), Made in India, Zen ENC Mic, 13mm Bass Drivers, Bluetooth 5.3 Ear Buds (Blue Moss)",
    img: "https://m.media-amazon.com/images/I/71vlByXS-JL._SL1500_.jpg",
    price: 2999,
    discount: 63,
    qty: 1,
    category: "earbud",
  },
  {
    id: 6,
    title:
      "Boult Audio X30 True Wireless in Ear Earbuds with 40H Playtime, Quad Mic ENC, 45ms Xtreme Low Latency, Made in India, Type-C Fast Charging, 3 Equalizer Modes (Rock, BoomX, Hi-Fi), BT 5.1 (Blue)",
    img: "https://m.media-amazon.com/images/I/71ey9w1JYTL._SL1500_.jpg",
    price: 4999,
    discount: 70,
    qty: 1,
    category: "earbud",
  },
  {
    id: 7,
    title:
      "boAt Airdopes 121v2 in-Ear True Wireless Earbuds with Upto 14 Hours Playback, 8MM Drivers, Battery Indicators, Lightweight Earbuds & Multifunction Controls (Active Black, with Mic)",
    img: "https://m.media-amazon.com/images/I/61o2urRxrcL._SL1500_.jpg",
    price: 2990,
    discount: 57,
    qty: 1,
    category: "earbud",
  },
  {
    id: 8,
    title:
      "Blaupunkt BTW07 ANC Moksha-30Db Bluetooth Truly Wireless In Ear Earbuds with Mic, Flip Top Rotatory Design, 40H Playtime, TurboVolt Fast Charging, Crispr Enc Tech, GameOn with 80Ms Low Latency (Black)",
    img: "https://m.media-amazon.com/images/I/31XeLoY52sL._SY300_SX300_.jpg",
    price: 5999,
    discount: 58,
    qty: 1,
    category: "earbud",
  },
  {
    id: 10,
    title: `pTron Bassbuds Fute 5.1 Bluetooth Truly Wireless Featherlite TWS in Ear Earbuds with Mic 25Hrs Playtime, 13Mm Dynamic Driver, Immersive Audio, Touch Control, Voice Assistance & Fast Charging (Black)`,
    img: "https://m.media-amazon.com/images/I/51PNGyUNvmL._SL1100_.jpg",
    price: 3299,
    discount: 79,
    qty: 1,
    category: "earbud",
  },
  {
    id: 11,
    title: `Boult Audio X1 Buds True Wireless in Ear Earbuds with 24H Playtime, Quad Mic ENC, Made in India, Type-C Fast Charging, Environmental Noise Cancellation, 10mm Bass Drivers, TWS Airbass ear buds (Black)`,
    img: "https://m.media-amazon.com/images/I/71mT2gCHH+L._SL1500_.jpg",
    price: 6999,
    discount: 74,
    qty: 1,
    category: "earbud",
  },
  {
    id: 12,
    title: `Boult Audio Powerbuds True Wireless in Ear Earbuds with 120H Playtime, in-Built Powerbank, Type-C Fast Charging, Made in India, Pro+ Calling HD Mic, IPX7 Waterproof, Bluetooth Ear Buds TWS (Black)`,
    img: "https://m.media-amazon.com/images/I/71jrExswt4L._SL1500_.jpg",
    price: 8999,
    discount: 83,
    qty: 1,
    category: "earbud",
  },
  {
    id: 13,
    title: `Noise Buds Vs104 Bluetooth Truly Wireless in Ear Earbuds with Mic, 30-Hours of Playtime, Instacharge, 13Mm Driver and Hyper Sync (Charcoal Black)`,
    img: "https://m.media-amazon.com/images/I/51cjIEYU8BL._SL1500_.jpg",
    price: 3499,
    discount: 69,
    qty: 1,
    category: "earbud",
  },
  {
    id: 101,
    title: `Allen Solly Men's Regular Fit Polo`,
    img: "https://m.media-amazon.com/images/I/71eUwDk8z+L._UY879_.jpg",
    price: 1099,
    discount: 47,
    qty: 1,
    category: "tshirt",
  },
  {
    id: 102,
    title: `Veirdo Polo T Shirts for Men, Cotton Polo Neck T Shirts for Men, Half Sleeves Men Polo Tshirt, Classic Polo T Shirts for Men, Men's Regular Polo Shirt`,
    img: "https://m.media-amazon.com/images/I/51lP3VinwoL._UY879_.jpg",
    price: 1199,
    discount: 68,
    qty: 1,
    category: "tshirt",
  },
  {
    id: 103,
    title: `AUSK Men's Henley Neck Full Sleeves Regular Fit Cotton T-Shirts`,
    img: "https://m.media-amazon.com/images/I/7152RCSU4LL._UX569_.jpg",
    price: 1449,
    discount: 76,
    qty: 1,
    category: "tshirt",
  },
  {
    id: 104,
    title: `Lyned Mens Cotton Half Sleeve Striped Polo T Shirt with Collar`,
    img: "https://m.media-amazon.com/images/I/71pNnnaOIzS._UY741_.jpg",
    price: 2499,
    discount: 73,
    qty: 1,
    category: "tshirt",
  },
  {
    id: 105,
    title: `AELOMART Men's T Shirt-(Amt250105-P_Green)`,
    img: "https://m.media-amazon.com/images/I/71O1QaI-sbL._UY741_.jpg",
    price: 1499,
    discount: 67,
    qty: 1,
    category: "tshirt",
  },
  {
    id: 106,
    title: `Campus Sutra Men's Blue and White Ombre Dri-Fit Activewear T-Shirt Regular Fit for Casual Wear | Structured T-Shirt Crafted with Comfort Fit and High-Performance for Everyday Wear`,
    img: "https://m.media-amazon.com/images/I/61MjKYTzgQS._UX679_.jpg",
    price: 1449,
    discount: 67,
    qty: 1,
    category: "tshirt",
  },
  {
    id: 107,
    title: `EYEBOGLER Men's Striped Regular Fit T-Shirt (T428HS_Blue XL) EYEBOGLERMenRegularT-Shirt`,
    img: "https://m.media-amazon.com/images/I/51zPkF2QEDL._SY741._SX._UX._SY._UY_.jpg",
    price: 1299,
    discount: 69,
    qty: 1,
    category: "tshirt",
  },
  {
    id: 108,
    title: `Urbano Fashion Men's Graphic Printed Round Neck Half Sleeve Slim Fit Cotton T-Shirt`,
    img: "https://m.media-amazon.com/images/I/812LCdKokXL._UX679_.jpg",
    price: 999,
    discount: 63,
    qty: 1,
    category: "tshirt",
  },
  {
    id: 201,
    title: `AVANT Men's Ultra Light Running and Training Shoes`,
    img: "https://m.media-amazon.com/images/I/61rpE6+B6EL._UL1000_.jpg",
    price: 1599,
    discount: 59,
    qty: 1,
    category: "shoes",
  },
  {
    id: 202,
    title: `ASIAN Men's Thar-04 Sports Running,Walking & Gym Shoes with Eva Sole Extra Jump Casual Sneaker Shoes for Men's & Boy's…`,
    img: "https://m.media-amazon.com/images/I/610fN3RyKFL._UL1100_.jpg",
    price: 649,
    discount: 19,
    qty: 1,
    category: "shoes",
  },
  {
    id: 203,
    title: `ASIAN Crystal-13 Sports Running,Walking & Gym Shoes with Crystal Cushion Technology Lightweight Casual Sneaker Shoes for Men's & Boy's`,
    img: "https://m.media-amazon.com/images/I/51rdBvOe1+L._UL1100_.jpg",
    price: 2299,
    discount: 45,
    qty: 1,
    category: "shoes",
  },
  {
    id: 204,
    title: `ASIAN Men's Wonder-13 Sports Running Shoes`,
    img: "https://m.media-amazon.com/images/I/61utX8kBDlL._UL1100_.jpg",
    price: 699,
    discount: 25,
    qty: 1,
    category: "shoes",
  },
  {
    id: 205,
    title: `BRUTON Men's Sports Shoes Sports`,
    img: "https://m.media-amazon.com/images/I/71A7mJgXCxL._UL1500_.jpg",
    price: 1299,
    discount: 70,
    qty: 1,
    category: "shoes",
  },
  {
    id: 206,
    title: `Campus Men's Hurricane Running Shoes`,
    img: "https://m.media-amazon.com/images/I/61+E6-WZBGL._UL1440_.jpg",
    price: 1299,
    discount: 46,
    qty: 1,
    category: "shoes",
  },
  {
    id: 207,
    title: `AVANT Men's Ultra Light Running and Training Shoes`,
    img: "https://m.media-amazon.com/images/I/61rpE6+B6EL._UL1000_.jpg",
    price: 1599,
    discount: 59,
    qty: 1,
    category: "shoes",
  },
  {
    id: 208,
    title: `Skechers Mens Glide-Step Sport - New Approa Casual Shoe`,
    img: "https://m.media-amazon.com/images/I/81+AshsrWXL._UL1500_.jpg",
    price: 7449,
    discount: 54,
    qty: 1,
    category: "shoes",
  },
  {
    id: 209,
    title: `Reebok Men's Energy Runner LP Nacho/Conavy/None Running Shoes`,
    img: "https://m.media-amazon.com/images/I/41dXa2CVvPL.jpg",
    price: 2499,
    discount: 50,
    qty: 1,
    category: "shoes",
  },
  {
    id: 210,
    title: `ASIAN Men's Wonder-13 Sports Running Shoes`,
    img: "https://m.media-amazon.com/images/I/616zTSviLpL._UL1100_.jpg",
    price: 699,
    discount: 25,
    qty: 1,
    category: "shoes",
  },
  {
    id: 211,
    title: `Adidas Mens Response Solar Running Shoe`,
    img: "https://m.media-amazon.com/images/I/714a6H-+ygL._UL1500_.jpg",
    price: 7599,
    discount: 46,
    qty: 1,
    category: "shoes",
  },
  {
    id: 212,
    title: `Adidas Mens Streetgaze M Running Shoes`,
    img: "https://m.media-amazon.com/images/I/71XSP9IVf5L._UL1500_.jpg",
    price: 4799,
    discount: 50,
    qty: 1,
    category: "shoes",
  },
  {
    id: 301,
    title: `FLEXIMAA Women's Cotton Plain V Neck Half Sleeve T-Shirt`,
    img: "https://m.media-amazon.com/images/I/61x8EYIm8hL._UL1500_.jpg",
    price: 699,
    discount: 55,
    qty: 1,
    category: "tshirtwomen",
  },
  {
    id: 302,
    title: `TRUEREVO Round Neck Half Sleeve Dry Fit Yoga Workout T Shirt for Women`,
    img: "https://m.media-amazon.com/images/I/71BLosl4pDL._UL1400_.jpg",
    price: 899,
    discount: 17,
    qty: 1,
    category: "tshirtwomen",
  },
  {
    id: 303,
    title: `LEOTUDE Cotton Blend Half Sleeve Oversized T-Shirts for Women's`,
    img: "https://m.media-amazon.com/images/I/61iKv6-unXL._UL1500_.jpg",
    price: 1099,
    discount: 73,
    qty: 1,
    category: "tshirtwomen",
  },
  {
    id: 304,
    title: `LEOTUDE Cotton Blend Half Sleeve Oversized Back Printed Women's T-Shirt`,
    img: "https://m.media-amazon.com/images/I/71P5TSBvg9L._UL1500_.jpg",
    price: 1099,
    discount: 67,
    qty: 1,
    category: "tshirtwomen",
  },
];
